version: '3.8'

services:
  aplcicd:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APLCICD_PORT=8080
      - APLCICD_HOME=/app/aplcicd
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "dyalog", "-script", "-e", "APLCICD.HealthCheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - aplcicd-network

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - aplcicd
    networks:
      - aplcicd-network

networks:
  aplcicd-network:
    driver: bridge

volumes:
  aplcicd-data: